### ISSUE TITLE
Allow us to use system googletest please.

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [azubieta/xdg-utils#12]
You have hard coded to clone googletest. In debian we cannot make network calls.

CMake Error at /usr/share/cmake-3.13/Modules/ExternalProject.cmake:2329 (message):
  error: could not find git for clone of googletest
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/ExternalProject.cmake:3105 (_ep_add_download_command)
  tests/fetch_and_build_gtest.cmake:5 (externalproject_add)
  tests/CMakeLists.txt:2 (include)

Please allow us to use system googletest.
Thanks

**Comment by azubieta** [comment]
Sure, I suppose that you will use a cmake config call like this 
`cmake -DGTEST_ROOT=/usr/src/gtest -DXDG_UTILS_TESTS=True ..`

**Comment by azubieta** [comment]
also made a new release for you: v1.0.1
