### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [azubieta/xdg-utils#14]
While packaging for debian I ran into lintian error for minor typo.
src/DesktopEntry/AST/Group.cpp:                    throw std::runtime_error("Group Header cannot be emtpy");
src/DesktopEntry/AST/Group.cpp:                    throw std::runtime_error("Group Header cannot be emtpy");

emtpy should be empty I would think :)

**Comment by azubieta** [comment]
Fixed. Thanks for reporting. Do you need a new release for it?

**Comment by ScarlettGatelyMoore** [comment]
Nah, that is not necessary, it is already in the review stage for upload. thank you

**Comment by azubieta** [comment]
You welcome :)
